CREATE TABLE IF NOT EXISTS make (
    `id` INT,
    `name` VARCHAR(12) CHARACTER SET utf8,
    `image` VARCHAR(3) CHARACTER SET utf8
);
INSERT INTO make VALUES
    (0,'Alfa Romeo','''""'),
    (1,'Aston Martin','''""'),
    (2,'Audi','''""'),
    (3,'Bentley','''""'),
    (4,'BMW','''""'),
    (5,'Cadillac','''""'),
    (6,'Chery','''""'),
    (7,'Chevrolet','''""'),
    (8,'Chrysler','''""'),
    (9,'Citroen','''""'),
    (10,'Dacia','''""'),
    (11,'Daewoo','''""'),
    (12,'Daihatsu','''""'),
    (13,'DFM','''""'),
    (14,'Dodge','''""'),
    (15,'Ferrari','''""'),
    (16,'Fiat','''""'),
    (17,'Ford','''""'),
    (18,'Geely','''""'),
    (19,'Honda','''""'),
    (20,'Hyundai','''""'),
    (21,'Infiniti','''""'),
    (22,'Isuzu','''""'),
    (23,'Jaguar','''""'),
    (24,'Jeep','''""'),
    (25,'Kia','''""'),
    (26,'Lada','''""'),
    (27,'Lamborghini','''""'),
    (28,'Lancia','''""'),
    (29,'Land Rover','''""'),
    (30,'Maserati','''""'),
    (31,'Mazda','''""'),
    (32,'Mercedes','''""'),
    (33,'Mini','''""'),
    (34,'Mitsubishi','''""'),
    (35,'Nissan','''""'),
    (36,'Opel','''""'),
    (37,'Peugeot','''""'),
    (38,'Porsche','''""'),
    (39,'Proton','''""'),
    (40,'Renault','''""'),
    (41,'Rover','''""'),
    (42,'Saab','''""'),
    (43,'Seat','''""'),
    (44,'Skoda','''""'),
    (45,'Smart','''""'),
    (46,'SsangYong','''""'),
    (47,'Subaru','''""'),
    (48,'Suzuki','''""'),
    (49,'Tata','''""'),
    (50,'Tofaş','''""'),
    (51,'Toyota','''""'),
    (52,'Volkswagen','''""'),
    (53,'Volvo','''""');